{% set name = "compas_view2" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 67ac211bbdd1f2a4dd10f89650a7c71141b6f09babbf7e9d69cbb85d22ebf650

build:
  number: 0
  skip: true  # [py<36 or py>38]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - cython
    - compas >=1.0
    - python.app    # [osx]
    - freeglut      # [win]
    - freetype-py
    - pyside2
    - pyopengl
    # - pyopengl-accelerate

test:
  imports:
    - compas_view2

about:
  home: https://github.com/compas-dev/compas_view2
  license: MIT
  license_file: LICENSE
  summary: Second generation viewers for the COMPAS framework
  dev_url: https://github.com/compas-dev/compas_view2
  doc_url: https://compas.dev/compas_view2

extra:
  recipe-maintainers:
    - brgcode
    - licini
